sudo: required
services: 
  - docker

before_install:
  - docker build -t react-prod:0.1 -f Dockerfile.prev .

script:
  - docker run --name react-prod-0.1 react-prod:0.1 npm run test:unit -- --coverage