name: React build
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code. # 레포지터리의 체크아웃
        uses: actions/checkout@master
      
      - name: Cache node modules    # node modules 캐싱
        uses: actions/cache@v1
        with: 
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies  # 의존파일 설치
        run: npm install
      
      - name: Build                 # React Build
        run: npm run build  
