#   * 진행순서[공통]
#   [0] 레포지터리 체크아웃 - (O)
#   [1] 캐싱 사용 node_modules - (O)
#   [2] npm 의존성 설치 - (O)
#   [3] Build(dev OR prod) - (O)
#   [4] Test - (O)
#   [5] 도커 이미지 생성 - (X) 
#   [6] Push 도커 이미지 - (X)


name: React development mode
on: 
  push: 
    branches:
      - master

env:
  IMAGE_NAME: jangbuda-front-app:dev

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout source code  # [0] Repo 체크아웃
        uses: actions/checkout@v1
      
      - name: Caching node_modules  # [1] node_modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-key: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}
      
      - name: Install dependencies   # [2] 의존성 설치
        run: npm install
      
      - name: Build                  # [3] 앱 빌드
        run: npm run build

      - name: Test                   # [4] 테스트 작업
        run: npm run test

      - name: Build image            # [5] 도커 이미지 생성
        run: docker build -t $IMAGE_NAME -f Dockerfile.dev .
      
      # [6] 도커 이미지 푸시